"""Finite-strain framework for anisotropic soft-tissue remodeling."""

from ._version import __version__
from .architecture import (
    MultiFiberMaterialParameters,
    discrete_nematic_coherence,
    discrete_nematic_distribution,
    element_adjacency_edges,
    element_graph_laplacian,
    multifiber_cauchy_stress,
    multifiber_first_piola_stress,
    multifiber_invariants,
    multifiber_strain_energy_density,
    nematic_graph_roughness,
    regularize_nematic_field,
    regularize_scalar_field,
    scalar_graph_roughness,
    theoretical_nematic_coherence,
)
from .multifiber_finite_element import (
    MultiFiberFiniteElementResult,
    assemble_multifiber_internal_energy_and_force,
    solve_multifiber_displacement_controlled_equilibrium,
)
from .coupling import (
    PolarimetryInitializedResult,
    PolarimetryRemodelingConfig,
    run_polarimetry_initialized_remodeling,
)
from .equilibrium_remodeling import (
    EquilibriumRemodelingConfig,
    EquilibriumRemodelingResult,
    run_equilibrium_remodeling,
)
from .finite_element import (
    FiniteElementConfig,
    FiniteElementResult,
    StructuredQuadMesh,
    assemble_internal_energy_and_force,
    element_centroids,
    rectangular_quad_mesh,
    sample_nematic_image_to_elements,
    solve_displacement_controlled_equilibrium,
)
from .identification import (
    BootstrapResult,
    MaterialFitResult,
    MaterialParameterMap,
    MechanicalDataset,
    build_multiaxial_protocol_dataset,
    fit_material_parameters,
    local_sensitivity_matrix,
    parametric_bootstrap_material_fit,
    predict_dataset_stress,
    weighted_residuals,
)
from .material import MaterialParameters, cauchy_stress, first_piola_stress, strain_energy_density
from .polarimetry import (
    PolarimetryStructureResult,
    RetardanceCalibration,
    canonicalize_nematic_azimuth,
    local_nematic_coherence,
    polarimetry_to_structure,
    retardance_to_order_proxy,
)
from .orientation import (
    angle_to_vector,
    nematic_angle_difference,
    orientation_tensor,
    vector_to_angle,
)
from .remodeling import RemodelingParameters, update_fiber_orientation, update_structural_order
from .simulation import SimulationConfig, SimulationResult, run_homogeneous_remodeling
from .spatial import (
    SpatialSimulationConfig,
    SpatialSimulationResult,
    compatible_shear_extension_deformation,
    nematic_field_statistics,
    rectangular_grid,
    run_spatial_remodeling,
    synthetic_fiber_field,
    synthetic_structural_order_field,
)
from .synthetic import (
    SyntheticPolarimetryBenchmark,
    synthetic_polarimetry_benchmark,
)
from .validation import (
    ChallengeEvaluation,
    PublicSyntheticChallenge,
    SyntheticValidationChallenge,
    ValidationMetrics,
    create_synthetic_validation_challenge,
    evaluate_synthetic_challenge,
    perturb_synthetic_architecture,
    validation_metrics,
)
from .stimuli import (
    directional_stretch_stimulus,
    equilibrium_structural_order,
    hill_activation,
    principal_stretch_direction,
)

__all__ = [
    "__version__",
    "ChallengeEvaluation",
    "PublicSyntheticChallenge",
    "SyntheticValidationChallenge",
    "ValidationMetrics",
    "create_synthetic_validation_challenge",
    "evaluate_synthetic_challenge",
    "perturb_synthetic_architecture",
    "validation_metrics",
    "BootstrapResult",
    "MaterialFitResult",
    "MaterialParameterMap",
    "MechanicalDataset",
    "build_multiaxial_protocol_dataset",
    "fit_material_parameters",
    "local_sensitivity_matrix",
    "parametric_bootstrap_material_fit",
    "predict_dataset_stress",
    "weighted_residuals",
    "MultiFiberFiniteElementResult",
    "MultiFiberMaterialParameters",
    "assemble_multifiber_internal_energy_and_force",
    "discrete_nematic_coherence",
    "discrete_nematic_distribution",
    "element_adjacency_edges",
    "element_graph_laplacian",
    "multifiber_cauchy_stress",
    "multifiber_first_piola_stress",
    "multifiber_invariants",
    "multifiber_strain_energy_density",
    "nematic_graph_roughness",
    "regularize_nematic_field",
    "regularize_scalar_field",
    "scalar_graph_roughness",
    "solve_multifiber_displacement_controlled_equilibrium",
    "theoretical_nematic_coherence",
    "EquilibriumRemodelingConfig",
    "EquilibriumRemodelingResult",
    "FiniteElementConfig",
    "FiniteElementResult",
    "StructuredQuadMesh",
    "SyntheticPolarimetryBenchmark",
    "MaterialParameters",
    "PolarimetryInitializedResult",
    "PolarimetryRemodelingConfig",
    "PolarimetryStructureResult",
    "RetardanceCalibration",
    "RemodelingParameters",
    "SimulationConfig",
    "SimulationResult",
    "SpatialSimulationConfig",
    "SpatialSimulationResult",
    "angle_to_vector",
    "assemble_internal_energy_and_force",
    "canonicalize_nematic_azimuth",
    "cauchy_stress",
    "compatible_shear_extension_deformation",
    "directional_stretch_stimulus",
    "element_centroids",
    "equilibrium_structural_order",
    "first_piola_stress",
    "hill_activation",
    "local_nematic_coherence",
    "nematic_angle_difference",
    "nematic_field_statistics",
    "orientation_tensor",
    "principal_stretch_direction",
    "polarimetry_to_structure",
    "retardance_to_order_proxy",
    "rectangular_grid",
    "rectangular_quad_mesh",
    "run_equilibrium_remodeling",
    "run_spatial_remodeling",
    "sample_nematic_image_to_elements",
    "solve_displacement_controlled_equilibrium",
    "run_polarimetry_initialized_remodeling",
    "run_homogeneous_remodeling",
    "strain_energy_density",
    "synthetic_fiber_field",
    "synthetic_polarimetry_benchmark",
    "synthetic_structural_order_field",
    "update_fiber_orientation",
    "update_structural_order",
    "vector_to_angle",
]
